## LOAD SAPS Shapefile

In [1]:
import pandas as pd
import geopandas as gpd

In [ ]:
precinct_data = gpd.read_file("../data/Police_bounds.shp")

precinct_data.head()

,COMPNT_NM,CREATE_DT,VERSION,geometry
0,BOTSHABELO,20251205,1.4.2,"POLYGON ((26.77137 -29.21403, 26.7733 -29.2217..."
1,KHUBUSIDRIFT,20251205,1.4.2,"POLYGON ((27.72842 -32.53051, 27.72842 -32.531..."
2,STUTTERHEIM,20251205,1.4.2,"POLYGON ((27.50201 -32.44217, 27.49884 -32.465..."
3,MOTHERWELL,20251205,1.4.2,"POLYGON ((25.61061 -33.81772, 25.60713 -33.822..."
4,KWADWESI,20251205,1.4.2,"POLYGON ((25.45586 -33.83107, 25.4666 -33.8334..."

## Load crime stats excel

In [ ]:
crime_data = pd.read_excel("../data/2025-2026_-_3rd_Quarter_WEB.xlsx", sheet_name="RAW Data", header=1)
crime_data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Comparison - 3rd quarter (October to December - 2021 to 2025),Unnamed: 8,8,...,61,62,Unnamed: 28,76,73,77,74,79,80,Unnamed: 35
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Comparison - 3rd quarter (October to December ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Crime_Category National contribution\nplacement,Crime_Category Provincial contribution\nplacement,Comp level,Station Crime_Category,Station,District,Province,Crime_Category,Code,2021-10-01 00:00:00,...,2025-11-01 00:00:00,2025-12-01 00:00:00,October 2025 to \nDecember 2025,National contribution\nplacement,National count diff\nplacement,Provincial contribution\nplacement,Provincial count diff\nplacement,Count direction,Count offence group,No
2,Murder Station 595,Eastern Cape Murder Station 109,Station,Aberdeen Murder,Aberdeen,Sarah Baartman District,Eastern Cape,Murder,1,1,...,2,0,2,595,448,109,83,Stabilized,17 Community reported serious Crime,7085
3,Attempted murder Station 864,Eastern Cape Attempted murder Station 128,Station,Aberdeen Attempted murder,Aberdeen,Sarah Baartman District,Eastern Cape,Attempted murder,2,0,...,0,0,0,864,555,128,84,Stabilized,17 Community reported serious crime,7086
4,Culpable homicide Station 830,Eastern Cape Culpable homicide Station 120,Station,Aberdeen Culpable homicide,Aberdeen,Sarah Baartman District,Eastern Cape,Culpable homicide,3,1,...,0,0,1,830,1141,120,197,Decreased,0,7087